"""
FlowState: Keystroke Dynamics Cognitive Load Estimator
=======================================================
report.py — Research Evaluation Report Generator

Produces a self-contained README results section and a formatted
comparison table that can be directly pasted into a paper or lab report.

Run this after train.py and validate.py to auto-generate:
  - reports/results_table.md   (README-ready markdown)
  - reports/results_table.csv  (machine-readable)
  - reports/louo_table.md      (multi-user results, if available)

The README section follows the standard structure expected in
ML systems papers: model comparison table, per-user breakdown,
ablation notes, and reproducibility instructions.
"""

from __future__ import annotations
import logging
from pathlib import Path
from datetime import datetime

import pandas as pd
import numpy as np

import sys
sys.path.insert(0, str(Path(__file__).parent))
from config import REPORTS_DIR, ISOLATION_FOREST_PARAMS, ONE_CLASS_SVM_PARAMS, LOF_PARAMS

log = logging.getLogger(__name__)


# ── Markdown table helpers ────────────────────────────────────────────────────

def _md_table(df: pd.DataFrame, bold_col: str | None = None,
              best_is_max: bool = True) -> str:
    """
    Render a DataFrame as a GitHub-flavoured Markdown table.
    Optionally bold the best value in a numeric column.
    """
    cols  = list(df.columns)
    lines = []

    # Header
    lines.append("| " + " | ".join(str(c) for c in cols) + " |")
    lines.append("| " + " | ".join("---" for _ in cols) + " |")

    # Find best row index for bolding
    best_idx = None
    if bold_col and bold_col in df.columns:
        numeric = pd.to_numeric(df[bold_col], errors="coerce")
        if best_is_max:
            best_idx = numeric.idxmax()
        else:
            best_idx = numeric.idxmin()

    for i, row in df.iterrows():
        cells = []
        for c in cols:
            val = str(row[c])
            if c == bold_col and i == best_idx:
                val = f"**{val}**"
            cells.append(val)
        lines.append("| " + " | ".join(cells) + " |")

    return "\n".join(lines)


# ── Section generators ────────────────────────────────────────────────────────

def _section_header(title: str) -> str:
    return f"\n## {title}\n"


def _model_config_table() -> str:
    rows = [
        {"Model": "IsolationForest",
         "n_estimators": ISOLATION_FOREST_PARAMS["n_estimators"],
         "Key Param": f"contamination={ISOLATION_FOREST_PARAMS['contamination']}",
         "Complexity": "O(n log n)"},
        {"Model": "OneClassSVM",
         "n_estimators": "—",
         "Key Param": f"nu={ONE_CLASS_SVM_PARAMS['nu']}, kernel={ONE_CLASS_SVM_PARAMS['kernel']}",
         "Complexity": "O(n² · d)"},
        {"Model": "LocalOutlierFactor",
         "n_estimators": "—",
         "Key Param": f"n_neighbors={LOF_PARAMS['n_neighbors']}",
         "Complexity": "O(n² · d)"},
    ]
    return _md_table(pd.DataFrame(rows))


# ── Main report assembler ─────────────────────────────────────────────────────

def generate_report(
    model_comparison_csv: Path | None = None,
    louo_csv:             Path | None = None,
    personalised_csv:     Path | None = None,
    output_dir:           Path = REPORTS_DIR,
) -> str:
    """
    Assemble a complete Results section in Markdown.

    Parameters
    ----------
    model_comparison_csv : Path to reports/model_comparison.csv (from train.py)
    louo_csv             : Path to reports/louo_results.csv (from multi_user.py)
    personalised_csv     : Path to reports/personalised_results.csv
    output_dir           : Directory to save the report

    Returns
    -------
    str  Full Markdown report text.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = []

    lines.append("# FlowState — Experimental Results\n")
    lines.append(f"> Auto-generated by `report.py` on {now}.\n")
    lines.append("> All results are reproducible by running `src/train.py` "
                 "then `src/validate.py`.\n")

    # ── 1. Feature Description ──
    lines.append(_section_header("1. Feature Space"))
    lines.append(
        "FlowState extracts a 7-dimensional feature vector per rolling window "
        f"(window size = 50 keystrokes). Features extend standard mean/std "
        "summaries with scale-normalised, distributional, and signal-complexity "
        "descriptors.\n"
    )
    feat_rows = [
        {"Feature": "mean_iki",        "Type": "Central tendency",  "Fatigue sensitivity": "↑ (slowdown)"},
        {"Feature": "std_iki",         "Type": "Dispersion",        "Fatigue sensitivity": "↑ (variability)"},
        {"Feature": "coeff_variation", "Type": "Norm. dispersion",  "Fatigue sensitivity": "↑ (speed-independent)"},
        {"Feature": "skewness",        "Type": "Shape",             "Fatigue sensitivity": "↑ (hesitation pauses)"},
        {"Feature": "entropy",         "Type": "Information",       "Fatigue sensitivity": "↑ (rhythm chaos)"},
        {"Feature": "hjorth_mobility", "Type": "EEG-inspired",      "Fatigue sensitivity": "↓ (frequency drop)"},
        {"Feature": "excess_kurtosis", "Type": "Tail detection",    "Fatigue sensitivity": "↑ (attentional lapses)"},
    ]
    lines.append(_md_table(pd.DataFrame(feat_rows)))
    lines.append("")

    # ── 2. Model Configurations ──
    lines.append(_section_header("2. Model Configurations"))
    lines.append(
        "All models are wrapped in a `sklearn.Pipeline` with a prepended "
        "`StandardScaler`. Training uses only presumed-normal (rested) windows.\n"
    )
    lines.append(_model_config_table())
    lines.append("")

    # ── 3. Single-User Evaluation ──
    lines.append(_section_header("3. Single-User Anomaly Detection Results"))
    lines.append(
        "Evaluation uses time-block pseudo-labelling: first 33% of session = "
        "normal (+1), last 33% = fatigued (−1), middle 34% excluded. "
        "Positive class = fatigued.\n"
    )

    if model_comparison_csv and Path(model_comparison_csv).exists():
        df_cmp = pd.read_csv(model_comparison_csv)
        # Drop summary rows if present
        df_cmp = df_cmp[~df_cmp["Model"].astype(str).str.startswith("MEAN")]
        lines.append(_md_table(df_cmp, bold_col="AUC_ROC", best_is_max=True))
        lines.append("")

        # Save clean CSV
        df_cmp.to_csv(output_dir / "results_table.csv", index=False)

        # Interpret best model
        auc_col = pd.to_numeric(df_cmp["AUC_ROC"], errors="coerce")
        best_model = df_cmp.loc[auc_col.idxmax(), "Model"]
        best_auc   = auc_col.max()
        lines.append(
            f"**Best model**: `{best_model}` (AUC-ROC = {best_auc:.4f}). "
            "Bold values indicate best performance per metric.\n"
        )
    else:
        lines.append(
            "_Run `python src/train.py` to populate this table._\n\n"
            "| Model | Train_Time_s | Precision | Recall | F1 | AUC_ROC |\n"
            "| --- | --- | --- | --- | --- | --- |\n"
            "| IsolationForest | — | — | — | — | — |\n"
            "| OneClassSVM | — | — | — | — | — |\n"
            "| LocalOutlierFactor | — | — | — | — | — |\n"
        )

    # ── 4. Multi-User Results ──
    lines.append(_section_header("4. Multi-User Generalisation"))

    if louo_csv and Path(louo_csv).exists():
        df_louo = pd.read_csv(louo_csv)
        lines.append("**Leave-One-User-Out (LOUO) Cross-Validation**\n")
        lines.append(
            "Each user is held out as the test set; the model trains on all "
            "remaining users' rested-state data. This evaluates *cross-user "
            "generalisation* without any per-user calibration.\n"
        )
        lines.append(_md_table(df_louo))
        lines.append("")
    else:
        lines.append(
            "LOUO results pending multi-user data collection. "
            "See `src/multi_user.py` for the experimental protocol.\n\n"
            "**Planned study design:**\n"
            "- N = 10 participants (target; power analysis: Cohen's d = 0.5, "
            "α = 0.05, power = 0.80)\n"
            "- 60-minute typing session per participant\n"
            "- Induced-load protocol: A → B → A → B → A phases (12 min each)\n"
            "- Concurrent NASA-TLX ratings every 10 minutes\n"
            "- Both LOUO and personalised evaluation reported\n"
        )

    if personalised_csv and Path(personalised_csv).exists():
        df_pers = pd.read_csv(personalised_csv)
        lines.append("**Personalised (Per-User Calibration) Evaluation**\n")
        lines.append(
            "Model trained on each user's own rested baseline "
            "(first 50 windows). Compared with LOUO to quantify the "
            "benefit of user-specific calibration.\n"
        )
        lines.append(_md_table(df_pers))
        lines.append("")

    # ── 4.5 Interpretability Analysis ──
    lines.append(_section_header("4.5 Interpretability Analysis — Feature Contributions"))

    contribution_md = output_dir / "feature_contribution.md"
    if contribution_md.exists():
        lines.append(contribution_md.read_text(encoding="utf-8"))
    else:
        # Auto-generate it now
        try:
            import sys as _sys
            _sys.path.insert(0, str(Path(__file__).parent))
            from feature_analysis import generate_feature_contribution_report
            contrib_df = generate_feature_contribution_report(output_dir)

            lines.append(
                "Feature contribution analysis reveals the behavioural signals "
                "that drive fatigue detection. "
                "See `reports/feature_contribution.csv` for the full ranked table.\\n"
            )
            lines.append("\n| Rank | Feature | Contribution |")
            lines.append("| --- | --- | --- |")
            for rank, row in enumerate(contrib_df.head(5).itertuples(), start=1):
                lines.append(f"| {rank} | `{row.feature}` | {row.contribution_pct:.1f}% |")
            lines.append("")
        except Exception as exc:
            lines.append(
                f"_Run `python src/feature_analysis.py` to generate this section. ({exc})_\\n"
            )

    # ── 5. Labelling Validity ──
    lines.append(_section_header("5. Labelling Validity"))
    lines.append(
        "The time-block pseudo-labelling strategy assumes monotonic fatigue "
        "accumulation (Ackerman & Kanfer, 2009). Validity is checked via:\n\n"
        "1. **NASA-TLX correlation**: Pearson r between model anomaly score "
        "and Weighted Workload Score (collected every 10 min).\n"
        "2. **Cohen's κ agreement**: Between pseudo-labels and TLX-derived "
        "labels. κ > 0.60 (substantial agreement) validates the approach.\n"
        "3. **Induced-load manipulation check**: In dual-task sessions, "
        "secondary task accuracy should drop in high-load phases (confirms "
        "the manipulation was effective).\n"
    )

    # ── 6. Reproducibility ──
    lines.append(_section_header("6. Reproducibility"))
    lines.append(
        "```bash\n"
        "# Install dependencies\n"
        "pip install scikit-learn pynput pandas scipy matplotlib joblib\n\n"
        "# Step 1: Collect a session (ESC to stop)\n"
        "python src/collector.py\n\n"
        "# Step 2: Train all models\n"
        "python src/train.py\n\n"
        "# Step 3: Generate ROC curves and AUC report\n"
        "python src/validate.py --session_csv data/features_live.csv\n\n"
        "# Step 4: Regenerate this report\n"
        "python src/report.py\n"
        "```\n"
    )

    # ── 7. References ──
    lines.append(_section_header("7. References"))
    refs = [
        "Hart, S. G., & Staveland, L. E. (1988). Development of NASA-TLX. *Advances in Psychology*, 52, 139–183.",
        "Epp, C., Lippold, M., & Mandryk, R. L. (2011). Identifying emotional states using keystroke dynamics. *Proc. ACM CHI*.",
        "Hjorth, B. (1970). EEG analysis based on time domain properties. *Electroencephalography & Clinical Neurophysiology*, 29(3), 306–310.",
        "Ackerman, P. L., & Kanfer, R. (2009). Test length and cognitive fatigue. *J. Experimental Psychology: Applied*, 15(2), 163–181.",
        "Liu, F. T., Ting, K. M., & Zhou, Z-H. (2008). Isolation forest. *Proc. ICDM*, 413–422.",
        "Revett, K. (2009). A survey of user authentication using keystroke dynamics. *ICCSA*.",
    ]
    for ref in refs:
        lines.append(f"- {ref}")
    lines.append("")

    full_report = "\n".join(lines)

    out_path = output_dir / "RESULTS.md"
    out_path.write_text(full_report, encoding="utf-8")
    log.info("Research report saved -> %s", out_path)

    return full_report


# ── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Generate FlowState results report")
    parser.add_argument("--model_csv",   type=Path, default=REPORTS_DIR / "model_comparison.csv")
    parser.add_argument("--louo_csv",    type=Path, default=REPORTS_DIR / "louo_results.csv")
    parser.add_argument("--pers_csv",    type=Path, default=REPORTS_DIR / "personalised_results.csv")
    parser.add_argument("--output_dir",  type=Path, default=REPORTS_DIR)
    args = parser.parse_args()

    logging.basicConfig(level="INFO", format="%(asctime)s | %(message)s")

    report = generate_report(
        model_comparison_csv=args.model_csv,
        louo_csv=args.louo_csv,
        personalised_csv=args.pers_csv,
        output_dir=args.output_dir,
    )
    print(report)
