"""
FlowState: Keystroke Dynamics Cognitive Load Estimator
=======================================================
train.py — Comparative model study:
    Isolation Forest vs One-Class SVM vs Local Outlier Factor

This script constitutes a reproducible experimental pipeline.  All
hyperparameters are defined in config.py; no magic numbers appear here.

Methodology
-----------
Because cognitive-load labelling is non-trivial (see validate.py), this
training stage operates in the unsupervised regime.  Each model is fit on
a presumed-clean (rested-state) training split and evaluated on the held-out
set using the pseudo-label strategy described in validate.py.
"""

import logging
import time
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor
from sklearn.svm import OneClassSVM
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import joblib

import sys
sys.path.insert(0, str(Path(__file__).parent))

from config import (
    ISOLATION_FOREST_PARAMS,
    ONE_CLASS_SVM_PARAMS,
    LOF_PARAMS,
    LABELED_DATA_PATH,
    MODELS_DIR,
    REPORTS_DIR,
    TEST_SIZE,
    RANDOM_STATE,
    LOG_LEVEL,
)
from features import FEATURE_NAMES

logging.basicConfig(level=LOG_LEVEL, format="%(asctime)s | %(levelname)s | %(message)s")
log = logging.getLogger(__name__)
warnings.filterwarnings("ignore", category=UserWarning)


# ── Model registry ─────────────────────────────────────────────────────────────

def build_model_registry() -> dict:
    """
    Return a dict of {name: sklearn Pipeline} for each candidate model.

    Each pipeline prepends a StandardScaler to ensure feature distributions
    are zero-centred and unit-variance — critical for SVM and LOF which are
    distance-sensitive, and good practice for IF.
    """
    registry = {
        "IsolationForest": Pipeline([
            ("scaler", StandardScaler()),
            ("model",  IsolationForest(**ISOLATION_FOREST_PARAMS)),
        ]),
        "OneClassSVM": Pipeline([
            ("scaler", StandardScaler()),
            ("model",  OneClassSVM(**ONE_CLASS_SVM_PARAMS)),
        ]),
        "LocalOutlierFactor": Pipeline([
            ("scaler", StandardScaler()),
            ("model",  LocalOutlierFactor(**LOF_PARAMS)),
        ]),
    }
    return registry


# ── Data loading ───────────────────────────────────────────────────────────────

def load_feature_matrix(path: Path = LABELED_DATA_PATH) -> tuple[np.ndarray, np.ndarray]:
    """
    Load the pre-extracted feature matrix and pseudo-labels.

    Expects a CSV with columns matching FEATURE_NAMES plus a 'label' column
    where 1 = normal (rested) and -1 = anomalous (fatigued).  Generated by
    validate.py via the time-block pseudo-labelling strategy.

    Returns
    -------
    X : np.ndarray, shape (n_samples, n_features)
    y : np.ndarray, shape (n_samples,)  — pseudo-labels {1, -1}
    """
    df = pd.read_csv(path)
    missing = [c for c in FEATURE_NAMES if c not in df.columns]
    if missing:
        raise ValueError(f"Missing feature columns in dataset: {missing}")
    X = df[FEATURE_NAMES].values
    y = df["label"].values if "label" in df.columns else np.ones(len(df))
    return X, y


# ── Training & evaluation ──────────────────────────────────────────────────────

def train_and_evaluate(
    X: np.ndarray,
    y: np.ndarray,
    registry: dict,
) -> pd.DataFrame:
    """
    Fit each model on the 'normal' training split and evaluate on the full
    held-out test set.

    For unsupervised anomaly detectors the convention is:
        predict() returns +1 (inlier / normal) or -1 (outlier / fatigued).

    Returns
    -------
    pd.DataFrame
        Comparison table with columns:
        Model | Train_Time_s | Precision | Recall | F1 | AUC_ROC
    """
    from sklearn.metrics import (
        precision_score, recall_score, f1_score,
        roc_auc_score, classification_report,
    )

    # Train only on presumed-normal samples (label == 1)
    normal_mask = y == 1
    X_train = X[normal_mask]

    X_test, y_test = X, y   # evaluate on entire dataset

    results = []

    for name, pipeline in registry.items():
        log.info("Training %s …", name)
        t0 = time.perf_counter()
        pipeline.fit(X_train)
        elapsed = time.perf_counter() - t0

        y_pred = pipeline.predict(X_test)

        # sklearn anomaly detectors return {1, -1}; map to {0, 1} for metrics
        y_pred_bin = (y_pred == -1).astype(int)   # 1 = predicted anomaly
        y_true_bin = (y_test == -1).astype(int)   # 1 = true anomaly

        # Decision scores for AUC-ROC
        if hasattr(pipeline.named_steps["model"], "decision_function"):
            scores = pipeline.decision_function(X_test)
            # Lower score = more anomalous; negate for ROC convention
            auc = roc_auc_score(y_true_bin, -scores)
        elif hasattr(pipeline.named_steps["model"], "score_samples"):
            scores = pipeline.score_samples(X_test)
            auc = roc_auc_score(y_true_bin, -scores)
        else:
            auc = np.nan

        metrics = {
            "Model":         name,
            "Train_Time_s":  round(elapsed, 4),
            "Precision":     round(precision_score(y_true_bin, y_pred_bin, zero_division=0), 4),
            "Recall":        round(recall_score(y_true_bin, y_pred_bin, zero_division=0), 4),
            "F1":            round(f1_score(y_true_bin, y_pred_bin, zero_division=0), 4),
            "AUC_ROC":       round(auc, 4) if not np.isnan(auc) else "N/A",
        }
        results.append(metrics)

        log.info(
            "%s → Precision=%.4f | Recall=%.4f | F1=%.4f | AUC=%.4f | t=%.2fs",
            name, metrics["Precision"], metrics["Recall"],
            metrics["F1"], auc if not np.isnan(auc) else 0, elapsed,
        )

        # Per-class report
        log.debug("\n%s", classification_report(y_true_bin, y_pred_bin,
                                                 target_names=["Normal", "Fatigued"]))

        # Persist model
        MODELS_DIR.mkdir(parents=True, exist_ok=True)
        joblib.dump(pipeline, MODELS_DIR / f"{name}.pkl")
        log.info("Saved model → %s", MODELS_DIR / f"{name}.pkl")

        # ── Permutation feature importance ──────────────────────────────────
        # Only computed for models that support predict() on unseen data.
        # LOF with novelty=True qualifies; all three models do here.
        try:
            from sklearn.inspection import permutation_importance as _perm_imp
            log.info("Computing permutation importance for %s …", name)
            perm = _perm_imp(
                pipeline,
                X_test,
                y_true_bin,
                n_repeats=10,
                random_state=RANDOM_STATE,
                scoring="roc_auc",
            )
            imp_df = pd.DataFrame({
                "feature":    FEATURE_NAMES,
                "importance": np.round(perm.importances_mean, 6),
                "std":        np.round(perm.importances_std,  6),
            }).sort_values("importance", ascending=False)

            imp_path = REPORTS_DIR / f"feature_importance_{name}.csv"
            imp_df.to_csv(imp_path, index=False)
            log.info("Feature importance saved → %s", imp_path)
            log.info("\n%s", imp_df.to_string(index=False))
        except Exception as exc:
            log.warning("Permutation importance failed for %s: %s", name, exc)

    return pd.DataFrame(results)


# ── Entry point ────────────────────────────────────────────────────────────────

def main():
    log.info("=" * 60)
    log.info("FlowState — Model Comparative Study")
    log.info("=" * 60)

    X, y = load_feature_matrix()
    log.info("Dataset: %d windows | %d features | %.1f%% anomalous",
             len(X), X.shape[1], 100 * (y == -1).mean())

    registry = build_model_registry()
    results_df = train_and_evaluate(X, y, registry)

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    out_path = REPORTS_DIR / "model_comparison.csv"
    results_df.to_csv(out_path, index=False)

    log.info("\n%s", results_df.to_string(index=False))
    log.info("Comparison table saved → %s", out_path)


if __name__ == "__main__":
    main()
